services:
  smerge:
    image: z0rr0/smerge:latest
    container_name: smerge
    user: "1000:1000"
    ports:
      - "43210:43210"
    volumes:
      - ./data:/data:ro
    restart: unless-stopped
    stop_grace_period: 10s
    logging:
      options:
        max-size: "5m"
        max-file: "2"
    deploy:
      resources:
        limits:
          memory: 32m
